/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KodeStencilInput {
    'label': string;
    'validator': { validate: (v) => boolean };
  }
}

declare namespace LocalJSX {
  interface KodeStencilInput extends JSXBase.HTMLAttributes {
    'label'?: string;
    'onInputChange'?: (event: CustomEvent<any>) => void;
    'validator'?: { validate: (v) => boolean };
  }

  interface IntrinsicElements {
    'kode-stencil-input': KodeStencilInput;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLKodeStencilInputElement extends Components.KodeStencilInput, HTMLStencilElement {}
  var HTMLKodeStencilInputElement: {
    prototype: HTMLKodeStencilInputElement;
    new (): HTMLKodeStencilInputElement;
  };

  interface HTMLElementTagNameMap {
    'kode-stencil-input': HTMLKodeStencilInputElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

